### PR TITLE
Adding script to convert packs file to string

### PR DESCRIPTION
**Pull request by PhillypHenning**
**Example packs.txt file**
```
- Pack1
- "Pack2"
- Pack3=v0.0.1
- "Pack4=v0.0.2"
- st2=v1.0.7
- circle_ci=v0.5.3
- packagecloud=v1.0.1
- aws=v1.2.1
- etcå
```

Environment variable created and loaded; 
```
echo $STACKSTORM_BITOPS_PACKS_LIST
> Pack1,Pack2,Pack3=v0.0.1,Pack4=v0.0.2,st2=v1.0.7,circle_ci=v0.5.3,packagecloud=v1.0.1,aws=v1.2.1,etc
```

### CODE REVIEW

**Review by mickmcgrath13 — CHANGES_REQUESTED** [review]
neat!  needs docs ;)

Also, we'll have to figure out what to do with this new file once we also support the  the ansible variables configuration file (which also configures packs).  More details here: https://github.com/bitovi/github-actions-deploy-stackstorm/issues/19

**Review by armab — COMMENTED** [review]
Yeah, similar to https://github.com/bitovi/github-actions-deploy-stackstorm/pull/32,

I believe just allowing to override the Ansible-st2 env vars would solve the pack installation problem: https://github.com/bitovi/github-actions-deploy-stackstorm/blob/a54470925280e198493586258104ac8f54a3a843/operations/deployment/ansible/vars/st2.yaml#L92-L93

So users could just do this in the custom Ansible `vars.yaml`:
```
st2_packs:
  - ansible
  - aws=v213
```
and that'll be passed directly to ansible-st2, instead of using another layer of generation. No other logic needed.

We'll start with st2.conf, then pack list, then we'll do RBAC, chatops configs, etc. etc, creating lots of bash generation and script/syntax handling which won't do any good for us.

**Comment by PhillypHenning** [comment]
Thanks for the input, I'll start on what's been suggested above.

**Comment by PhillypHenning** [comment]
I can update the script to export that variable; `ST2_PACKS` which would satisfy the current ansible lookup.... 

Would this not be the easiest path forward @armab ?

**Comment by armab** [comment]
Ansible has several layers of var precedence.

If we'll allow users to specify their custom `st2.yaml` Ansible vars in their repositories which will take priority over the whole https://github.com/bitovi/github-actions-deploy-stackstorm/blob/main/operations/deployment/ansible/vars/st2.yaml
that'll open the opportunity to configure everything that's defined in the https://github.com/stackStorm/ansible-st2#variables, - a lot of configuration, including pack install.

**Comment by PhillypHenning** [comment]
@mickmcgrath13 do we want this functionality added along with the custom st2 pack file

**Comment by armab** [comment]
This PR could be closed by the https://github.com/bitovi/github-actions-deploy-stackstorm/pull/32#discussion_r1066371372 as defining st2 packs as a list will be possible via Ansible vars.

**Comment by PhillypHenning** [comment]
Closed https://github.com/bitovi/github-actions-deploy-stackstorm/pull/32#discussion_r1066371372

**Pull request closed without merging**
